spring.application.name=auth_redis_demo
server.port=8080

# ==============================
# PostgreSQL
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5432/nithya
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update   
# create tables automatically
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true



# ==============================
# JWT
# ==============================
app.jwt.secret=8a9f4e23c7d14a89b1a7e6f3c2d9f5ab3e6c49d6c52f18b7a99dfe21f3c7a45b
app.jwt.expiration-ms=86400000


# ==============================
# Redis
# ==============================
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# Optional TTL config (example: 10 min default cache time)
# spring.cache.redis.time-to-live=600000

# ==============================
# Logging
# ==============================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
