spring.application.name=keycloak-demo

# Server
server.port=8081

# Keycloak Realm & Auth Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/new
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/new/protocol/openid-connect/certs

# PostgreSQL Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/nithya
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# (Optional but recommended for schema init)
spring.sql.init.mode=always

# (Optional but recommended for frontend integration)
# spring.web.cors.allowed-origins=http://localhost:3000
# spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
# Redis configuration
spring.redis.host=localhost
spring.redis.port=6379

